### ISSUE TITLE
Spiders are too slow

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite#2043]
In my survival play I've encountered a few minor issues with the AI.

Spiders move much too slowly, and attack slowly as well.
Guardians move on land.
Cows like to stay in the water much more than they should.

**Comment by SafwatHalaby** [comment]
Regarding water: Currently the mobs don't differentiate between it and land.
Spiders currently act pretty much like zombies.
I didn't touch the guardians yet.

**Comment by LogicParrot** [comment]
The water and guardian issues are fixed. Renaming the issue.

**Comment by Alcamech** [comment]
Hey, I am looking to contribute to Cuberite and saw this issue labeled as effort/easy and decided to give it a stab. I'm having trouble finding where the spiders speed is affected, could anyone point me in the right direction.

**Comment by NiLSPACE** [comment]
You'll most likely want to override the MoveToWayPoint method from [cMonster](https://github.com/cuberite/cuberite/blob/master/src/Mobs/Monster.cpp#L143) in [Spider.h](https://github.com/cuberite/cuberite/blob/master/src/Mobs/Spider.h) and [Spider.cpp](https://github.com/cuberite/cuberite/blob/master/src/Mobs/Spider.cpp). There are plans to completely change the way mobs work though: https://github.com/cuberite/cuberite/pull/3295.

**Comment by Alcamech** [comment]
@NiLSPACE Okay thanks.

**Comment by anguslmm** [comment]
Just checked, looks like this is still an issue. Spiders move at zombie speed, but tests in a local world show they should move at about the same speed as a player walking.

Is there any guidance on an exact speed? I'm going to start looking at where this is set in the mean time, and I'll use player base walking speed as a reference unless I hear different.

**Comment by anguslmm** [comment]
Upon looking at the code that handles walk speed, it looks like everything has the default `m_RelativeWalkSpeed` of 1 except for wolves, which set it to 2. The speed is not referenced in monsters.ini, where it probably belongs.

Thoughts? Should I rename this issue and start putting together appropriate speeds?

**Comment by peterbell10** [comment]
@anguslmm a setting in `monsters.ini` sounds perfect. Feel free to open a PR or ask questions if you need help.

**Comment by anguslmm** [comment]
Sweet, I'll get started. I'm having trouble finding a way to get data on relative moment speeds to use, but I'll go ahead and start the refactor necessary to move it into monsters.ini, then it can be easily changed to more correct values when we find a way, or by playing around until we get something that feels right.

**Comment by anguslmm** [comment]
So I've got that value moved to `monsters.ini`, no problem, but there's another need here.

Spiders actually move too fast when not aggressive, and too slow when aggressive. `Wolf.h` has `m_IsAngry`, but other monsters do not. So this brings up two additional changes I'd like to make to fully complete this:

- Move `m_IsAngry` and related functions into cPassiveAggressiveMonster, so that Spiders, Zombie Pigmen, Endermen, and anything else that needs this behavior can have it. This can be how spiders become aggressive at night now, etc.
- Add another setting, either a multiplier or raw value, to control what speed is set to when angry. Maybe even just to set run speed. This is substantially different between monsters.

Any concerns? And should I use a raw value or multiplier for run speed?

**Comment by madmaxoft** [comment]
Sounds good. Use a separate value (`PassiveSpeed` and `AngrySpeed`; aggressive-only mobs should only use `AngrySpeed`)

**Comment by peterbell10** [comment]
>Move m_IsAngry and related functions into cPassiveAggressiveMonster, so that Spiders, Zombie Pigmen, Endermen, and anything else that needs this behavior can have it. This can be how spiders become aggressive at night now, etc.

I think checking `cMonster::m_EMState == CHASING` should work for that.

**Comment by anguslmm** [comment]
> I think checking cMonster::m_EMState == CHASING should work for that.

Ok, that sounds right. State `ESCAPING` should probably be checked when determining speed too, so that passive monsters move quickly when attacked.

So I'll have `WalkSpeed` and `RunSpeed` in `monsters.ini`, and decide which one to use based on `m_EMState`. I'll leave `m_IsAngry` alone since it's outside the scope of this issue.

**Comment by jclever77** [comment]
Hey! I noticed that this PR never got merged, and after testing found that the spiders still seem to go slower than expected. Does this mean that this issue is still open to be fixed? If so, I'd like to give it a try.

**Comment by tigerw** [comment]
Sure! Maybe you can base it off that PR.

**Comment by jclever77** [comment]
@tigerw Can do!
