### ISSUE TITLE
Chests are invisible after Re-login

### ISSUE THREAD

**Issue by Seadragon91** [cuberite/cuberite#3403]
Client version:   1.10
Server OS:        Windows/Linux
Commit id:        (4e33569110d9a4e71b1d2fa4ea674225c8d36b88)
### Expected behavior

Chests / trapped chest / ender chest should be visble after re-login.
### Actual behavior

Chests are invisible.
### Steps to reproduce the behavior

1) Login with 1.11.2 client place chest
2) Re-login
3) Chest is not visible anymore

This affects 1.11.2 clients in 1.9 it works fine. Maybe a missing packet update or data value problem.

**Comment by NiLSPACE** [comment]
Are they back when you lief gin with a different MC version?

**Comment by Seadragon91** [comment]
I can see the blocks in 1.9, but not in 1.10 after re-login. Because of this I think a packet has been changed in 1.10.

**Comment by Pokechu22** [comment]
Are they quite literally _invisible_?  And if so, what does "invisible" mean?  Can you still see their hitbox if you look at them, and the model just isn't rendering?  (I'd check this myself but I don't have time to right now).

I don't think any packet would should be necessary to make chests visible; they should show up by default (except for in 1.10.1 and only 1.10.1, since 1.10.1 had some extra block entity requirements not present in 1.10.0 and 1.10.2)

**Comment by Seadragon91** [comment]
They are not rendered after re-login, but I can open them. If I open it or destroy a block near them, then they visible again.

**Comment by Pokechu22** [comment]
Hm.  I know invisible chests occur with [triple chests](https://bugs.mojang.com/browse/MC-34365), but that shouldn't ever happen with single chests.  There's also [MC-65874](https://bugs.mojang.com/browse/MC-65874), which involves chests not rendering even with single chests, but that was supposed to have been fixed in 14w32c (even though people are still claiming to experience it, but that seems to be a memory-related issue, and if other chests are displaying that's probably not it).

**Comment by Seadragon91** [comment]
I read that the current chunk update contains a field named `Block entities`, does the current protcol adds the blockentities?
http://wiki.vg/Protocol#Chunk_Data

**Comment by Pokechu22** [comment]
It adds them using the update block entities packet IIRC, instead of in the field there.

**Comment by Seadragon91** [comment]
I still have this problem maybe it's my PC, Can someone confirm it?

**Comment by mathiascode** [comment]
This is still a problem, and it's not only chests that are invisible. #3696

**Comment by spekdrum** [comment]
can't this issue be closed?

**Comment by Seadragon91** [comment]
Oh yes indeed, thanks ;)
